spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: db3,db4
      db3:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db3?characterEncoding=utf-8&serverTimezone=GMT&useSSL=true
        username: root
        password: root
      db4:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db4?characterEncoding=utf-8&serverTimezone=GMT&useSSL=true
        username: root
        password: root
    sharding:
      binding-tables: user
      default-database-strategy:
        inline:
          sharding-column: id
          algorithm-expression: db$->{id%2+3}
      tables:
        user:
          key-generator:
            column: id
            type: SNOWFLAKE
          table-strategy:
            inline:
              algorithm-expression: db$->{id%2+3}.user$->{id%3}
              sharding-column: id
    props:
      sql:
        show: true