spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: db0,db1
      db0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db0?characterEncoding=utf-8
        username: root
        password: root
      db1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db1?characterEncoding=utf-8
        username: root
        password: root

    sharding:
      default-database-strategy:
        standard:
          sharding-column: id
          precise-algorithm-class-name: com.shadingsphere.shardingdb.shadingsphere.PreciseAlgorithmClassName
        none:
          any: none
      default-data-source-name: db0
    props:
      sql:
        show: true