spring:
  shardingsphere:
    datasource:
      names: db2
      db2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db2?characterEncoding=utf-8&serverTimezone=GMT&useSSL=true
        username: root
        password: root
    sharding:
      tables:
        user:
          actual-data-nodes: db2.user$->{0..2}
          table-strategy:
#            inline:
#              sharding-column: id
#              algorithm-expression: user$->{id%3}
            standard:
              sharding-column: id
              precise-algorithm-class-name: com.shadingsphere.shardingtable.shadingsphere.PreciseAlgorithmClassName
          key-generator:
            column: id
            type: SNOWFLAKE
      binding-tables: user
  main:
    allow-bean-definition-overriding: true